# Generated by Django 6.0.6 on 2026-08-06 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('surname', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator('(?=.*\\+[0-9]{3}\\s?[0-9]{2}\\s?[0-9]{3}\\s?[0-9]{4,5}$)', 'Only ukrainian numbers allowed')])),
                ('age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('course', models.CharField(choices=[('FS', 'Fs'), ('QACX', 'Qacx'), ('JCX', 'Jcx'), ('JSCX', 'Jscx'), ('FE', 'Fe'), ('PCX', 'Pcx')], max_length=5)),
                ('course_format', models.CharField(choices=[('static', 'Static'), ('online', 'Online')], max_length=6)),
                ('course_type', models.CharField(choices=[('pro', 'Pro'), ('minimal', 'Minimal'), ('premium', 'Premium'), ('incubator', 'Incubator'), ('vip', 'Vip')], max_length=10)),
                ('status', models.CharField(blank=True, choices=[('In work', 'Inwork'), ('New', 'New'), ('Agreed', 'Agreed'), ('Disagreed', 'Disagreed'), ('Dubbing', 'Dubbing')], max_length=9, null=True)),
                ('sum', models.IntegerField(blank=True, null=True)),
                ('alreadyPaid', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-id'],
            },
        ),
    ]
