# Generated by Django 6.0.6 on 2026-08-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='group',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='manager',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
