# Generated by Django 6.0.6 on 2026-09-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='utm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
